version: '3.1'

services:
  main-db:
    image: 'postgres'
    container_name: 'main'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "2345:5432"

  test-db:
    image: 'postgres'
    container_name: 'test'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "2346:5432"
